---
- id: git-upstream-sync
  name: git-upstream-sync
  description: Sync forked repo with upstream
  entry: hooks/git-upstream-sync.sh
  language: script

- id: setup-commit-msg-hook
  name: setup-commit-msg-hook
  description: Check commit message format
  entry: hooks/setup-commit-msg-hook.sh
  language: script
